// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAz62Hsn-CbfvnU2DtdJB2mrKM-eRVa7bI",
    appId: '1:12154543021:android:550e9a9268e5520dfa9f24',
    //'1:523980747506:android:e88eee0f164ebdb75f166b'
    messagingSenderId: '12154543021',
    projectId: 'flutter-shop-app-4d0e6',
    storageBucket: 'flutter-shop-app-4d0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAz62Hsn-CbfvnU2DtdJB2mrKM-eRVa7bI",
    appId: '1:12154543021:ios:550e9a9268e5520dfa9f24',
    //1:523980747506:ios:160f9d084cab3ac15f166b',
    messagingSenderId: '12154543021',
    projectId: 'flutter-shop-app-4d0e6',
    storageBucket: 'flutter-shop-app-4d0e6.appspot.com',
    iosClientId:
        "12154543021-jo93u4kmktamrts30obofjtfpam7r1ev.apps.googleusercontent.com",
    //'523980747506-1fd8e8pg1ld5dvnn854b2pvnt6vjm9vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
